# Generated by Django 3.2 on 2022-09-11 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('category', models.CharField(choices=[('school', '学校'), ('work', '仕事'), ('hoby', '趣味'), ('private', 'プライベート')], max_length=100)),
            ],
        ),
    ]
